### ISSUE TITLE
 Question

### ISSUE THREAD

**Issue by zhang494** [phthinh/OFDM_802_16#1]
OFDM_RX_tb.v  in OFDM_RX_802_16 have some problems , the simulation cannot be stopped, and there is no output result。

**Comment by phthinh** [comment]
Hi Zhang, Did you use the Matlab files to generate the test vector for the simulation testbench? Could you provide further details so that I can get the exact problems?

**Comment by phthinh** [comment]
> OFDM_RX_tb.v in OFDM_RX_802_16 have some problems , the simulation cannot be stopped, and there is no output result。

Hi Zhang, Did you use the Matlab files to generate the test vector for the simulation testbench? Could you provide further details so that I can get the exact problems?

**Comment by zhang494** [comment]
Hi,&nbsp;thank you for replying to my question.&nbsp;Of course, I used the Matlab files to generate the test vector.&nbsp;The file "Ch_EstEqu" pin "DAT_CNT" cannot count to 255 and "car_cnt" cannot count to 199, resulting in the output flag bit "STB_O"&nbsp;not being changed to 1.




发件人:                                                                                                                        "phthinh/OFDM_802_16"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月19日(星期一) 下午5:48
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [phthinh/OFDM_802_16]  Question (#1)





 
Hi Zhang, Did you use the Matlab files to generate the test vector for the simulation testbench? Could you provide further details so that I can get the exact problems?

**Comment by phthinh** [comment]
> Hi,&nbsp;thank you for replying to my question.&nbsp;Of course, I used the Matlab files to generate the test vector.&nbsp;The file "Ch_EstEqu" pin "DAT_CNT" cannot count to 255 and "car_cnt" cannot count to 199, resulting in the output flag bit "STB_O"&nbsp;not being changed to 1. 发件人: "phthinh/OFDM_802_16" ***@***.***&gt;; 发送时间:&nbsp;2021年7月19日(星期一) 下午5:48 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [phthinh/OFDM_802_16] Question (#1) Hi Zhang, Did you use the Matlab files to generate the test vector for the simulation testbench? Could you provide further details so that I can get the exact problems? — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

Hi Zhang, It seems that the synchronization didn't work well with the generated data samples that are affected by non-ideal channels. In file OFDM_RX_wr_dat_in.m, the generated data samples are simulated with configurable timing offset and awgn factors. You can set SNR =50 to make sure these factors don't cause any issues.

**Comment by zhang494** [comment]
It turned out to be right. Thank you very much indeed.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "phthinh/OFDM_802_16"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月21日(星期三) 凌晨4:36
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [phthinh/OFDM_802_16]  Question (#1)





  
Hi,&nbsp;thank you for replying to my question.&nbsp;Of course, I used the Matlab files to generate the test vector.&nbsp;The file "Ch_EstEqu" pin "DAT_CNT" cannot count to 255 and "car_cnt" cannot count to 199, resulting in the output flag bit "STB_O"&nbsp;not being changed to 1. 发件人: "phthinh/OFDM_802_16" @.&gt;; 发送时间:&nbsp;2021年7月19日(星期一) 下午5:48 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [phthinh/OFDM_802_16] Question (#1) Hi Zhang, Did you use the Matlab files to generate the test vector for the simulation testbench? Could you provide further details so that I can get the exact problems? — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.
  
Hi Zhang, It seems that the synchronization didn't work well with the generated data samples that are affected by non-ideal channels. In file OFDM_RX_wr_dat_in.m, the generated data samples are simulated with configurable timing offset and awgn factors. You can set SNR =50 to make sure these factors don't cause any issues.
